site_name: TimeSeries - Arduino Library
site_url: https://miguelloureiro98.github.io/TimeSeries/
repo_url: https://github.com/MiguelLoureiro98/TimeSeries

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: teal
      accent: green
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: teal
      accent: green

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguel-santos-loureiro/
      name: Miguel Loureiro's LinkedIn page
    - icon: fontawesome/brands/github
      link: https://github.com/MiguelLoureiro98
      name: Miguel Loureiro's GitHub page

copyright: Copyright &copy; 2025 Miguel Loureiro

plugins:
  - search
  - mkdoxy:
      projects:
        TimeSeries: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src/ # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.h" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
            JAVADOC_AUTOBRIEF: True
            JAVADOC_BANNER: True
            JAVADOC_BLOCK: True

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
- Home: index.md
- First steps: installation.md
- API Reference: 
  - Main page: API_ref.md
  - API Index: TimeSeries/annotated.md
  - Namespace list: TimeSeries/namespaces.md
  - ts namespace: TimeSeries/namespacets.md
  - AR template class: TimeSeries/classts_1_1AR.md
  - MA template class: TimeSeries/classts_1_1MA.md
- Examples:
  - examples/index.md
  - Basic usage: examples/basics.md
  - Multi-step forecasting: examples/multi-step.md
  - Change model parameters: examples/change_param.md
- About: about.md

not_in_nav: |
  /TimeSeries/files.md
  /TimeSeries/dir_68267d1309a1af8e8297ef4c3efbcdba.md
  /TimeSeries/TimeSeries_8h.md
  /TimeSeries/TimeSeries_8h_source.md
  /TimeSeries/classes.md
  /TimeSeries/hierarchy.md
  /TimeSeries/modules.md
  /TimeSeries/pages.md
  /TimeSeries/class_members.md
  /TimeSeries/class_member_functions.md
  /TimeSeries/class_member_variables.md
  /TimeSeries/class_member_typedefs.md
  /TimeSeries/class_member_enums.md
  /TimeSeries/namespace_members.md
  /TimeSeries/namespace_member_functions.md
  /TimeSeries/namespace_member_variables.md
  /TimeSeries/namespace_member_typedefs.md
  /TimeSeries/namespace_member_enums.md
  /TimeSeries/functions.md
  /TimeSeries/macros.md
  /TimeSeries/variables.md
  /TimeSeries/links.md