name: examples

on:

  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  compile_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout custom library
        uses: actions/checkout@v4
        with:
          repository: MiguelLoureiro98/TimeSeries
          ref: main
          path: CustomTimeSeries

      - name: Compile examples
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: "*.ino"
          sketch-names-find-start: examples/