name: tests

on:

  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  compile_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout TimeSeries library
        uses: actions/checkout@v4
        with:
          repository: MiguelLoureiro98/TimeSeries
          ref: main
          path: CustomTimeSeries

      - name: Checkout ArduinoUnit
        uses: actions/checkout@v4
        with:
          repository: mmurdoch/arduinounit
          ref: main
          path: CustomArduinoUnit

      - name: Compile tests
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: "*.ino"
          sketch-names-find-start: extras/tests/